config/routes.rb
Spliddit::Application.routes.draw do
  
  resources :applications, path: "apps", only: [:index]

  post 'apps/rent/create', to: 'splitting_rent_instances#create'
  get 'apps/rent/demo', to: 'splitting_rent_instances#demo'
  resources :splitting_rent_instances, path: "apps/rent", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  post 'apps/goods/create', to: 'dividing_goods_instances#create'
  get 'apps/goods/demo', to: 'dividing_goods_instances#demo'
  resources :dividing_goods_instances, path: "apps/goods", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  post 'apps/credit/create', to: 'sharing_credit_instances#create'
  get 'apps/credit/demo', to: 'sharing_credit_instances#demo'
  resources :sharing_credit_instances, path: "apps/credit", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  resources :splitting_fare_instances, path: "apps/fare", only: [:index, :new]

  post 'apps/tasks/create', to: 'assigning_tasks_instances#create'
  get 'apps/tasks/demo', to: 'assigning_tasks_instances#demo'
  resources :assigning_tasks_instances, path: "apps/tasks", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  get '/about', to: 'static_pages#about'
  get '/feedback', to: 'feedbacks#feedback'
  get '/success', to: 'statuses#success'
  get '/error', to: 'statuses#error'
  get '/404', to: 'statuses#error404'
  get '/422', to: 'statuses#error500'
  get '/500', to: 'statuses#error500'

  post '/demo/create', to: 'demos#create'
  get '/demo/poll', to: 'demos#poll'

  post '/mailing_list/add', to: 'mailing_lists#mailing_list'

  post '/submit-feedback', to: 'feedbacks#submit_feedback'

  root to: "applications#index"
end

app/models/assigning_tasks_instance.rb
class AssigningTasksInstance < Instance

  def run(attempt)
    fname = "#{Rails.configuration.tmp_dir}/#{id}.txt"

    # build temp file for calling Java program
    File.delete(fname) if File.exist?(fname)
    File.open(fname, 'w+') do |f|
      # first line is number of agents, second line is number of items
      f.write("#{agents.count.to_s}\n")
      f.write("#{resources.count.to_s}\n")

      # for each item, write quantity
      resources.each do |r|
        f.write("#{r.id} #{r.quantity}\n")
      end

      # valuations
      valuations.each do |v|
        f.write("#{v.agent_id} #{v.resource_id} #{v.value}\n")
      end
    end

    # call Java
    allocation_str = `#{Rails.configuration.java_dir} -Djava.library.path=#{Rails.configuration.cplex_lib} -jar bin/tasks.jar #{fname}`

    if allocation_str.include? "failure"
      raise Error
    end

    utility = 0.0

    # create assignments
    assignments.delete_all
    allocation_str.each_line do |line|
      assignment_arr = line.split
      if assignment_arr[0] == "utility"
        utility = assignment_arr[1]
      end
      next unless assignment_arr.count == 4
      a = Assignment.new(ownership: assignment_arr[3].to_i)
      a.agent_id = assignment_arr[0].to_i
      a.resource_id = assignment_arr[1].to_i
      a.instance_id = id
      a.save

    end
    raise Error if assignments.count == 0

    equitability_notes(utility)
  end

  def equitability_notes(utility)
    agents.each do |a|
      str = "The distribution of tasks is equitable: each of the #{agents.count} participants was assigned tasks that they believed to be approximately #{sprintf("%0.02f", utility)}% of the total work, according to the submitted evaluations."
      a.update_attribute(:fairness_str, str)
    end
  end


  def max_task
    resources.sort_by {|r| r.quantity }.last
  end

  # validators
  def min_agents
    2
  end

  def max_agents
    15
  end

  def min_resources
    2
  end

  def max_resources
    100
  end

  def resource_types
    []
  end

  def valuations_sum
    100
  end

  def decimal_valuations
    true
  end

  def min_bid
    -1000
  end
end

app/controllers/assigning_tasks_instances_controller.rb
class AssigningTasksInstancesController < InstancesController
  def new
    @participants = 2
    @fixed_agents = false

    @resources = 3
    @resource_name = "Task"
    @instructions = "List each individiual task (chores, work shifts) as well as the number of times the task must be completed over the specified time frame."
    @show_types = false
    @show_descriptions = true
    @show_quantities = true    
    @resource_types = []
  end

  def create
    # TODO: factor this function out and add use the long name of the Application model
    instance = assigning_tasks_instance_builder(params)
    if instance && instance.separate_passwords
      flash[:success] = "<strong>Your Distributing Tasks instance has been created successfully!</strong> We are in the process of sending emails to all of the addresses listed, each containing a unique, private evaluation link. Once everyone has submitted their evaluations, we'll send another email with the final results. Thanks for using Spliddit!<br><br><a href = '#{root_url}apps/tasks'>Back to Dividing Goods information page</a>".html_safe
      redirect_to root_url + 'success'
    elsif instance && !instance.separate_passwords
      flash[:success] = "<strong>Your Distributing Tasks instance has been created successfully!</strong> Please direct everyone participating to <a href='#{root_url}apps/tasks/#{instance.id}?p=#{instance.passcode}'>#{root_url}apps/tasks/#{instance.id}?p=#{instance.passcode}</a> to submit their evaluations. Please make sure you copy the link before leaving this page.".html_safe
      redirect_to root_url + 'success'
    else
      flash[:error] = "We encountered a problem when trying to create your Distributing Tasks instance. (Perhaps one or more of your email addresses were invalid?) We apologize for the inconvenience. We hope you'll <a href = '#{root_url}apps/tasks/new'>try again</a>, and <a href= '#{feedback_path}'>contact us</a> if the error persists.".html_safe
      redirect_to root_url + 'error'
    end
  end

  def show
    if Instance.find(params[:id]).application.abbr != "tasks"
      flash[:error] = "The URL you specified is incorrect. Please ensure you have correctly copied the link."
      redirect_to root_url + 'error'
    else
      super

      # compute task with highest quantity for the valuations form
      @max_task = @instance.max_task
    end
  end
  
  def redirect(instance, password)
    redirect_to assigning_tasks_instance_path(instance, p: password)
  end
end

app/views/assigning_tasks_instances/_banner.html.erb
<div class="innerpage-banner">
    <div class="wrap">
        <div class="page-title">
            <h1>Distribute Tasks</h1>
        </div>
        <div class="banner-image">
            <%= image_tag "banners/assigning-chores.png", width: 246, height: 246, alt: "Distribute Tasks" %>
        </div>
    </div><!--.wrap-->
</div><!--.innerpage-banner-->

app/views/assigning_tasks_instances/_results.html.erb
<p class="lead-paragraph">Here are the results from the <%= link_to "Distributing Tasks App", root_url + 'apps/tasks' %>. Thank you for using Spliddit!</p>

<table class = "table">
  <thead>
    <tr>
      <td>Name</td>
      <td>Tasks</td>
    </tr>
  </thead>
  <tbody>
    <% @instance.agents.each do |agent| %>
      <tr>
        <td><%= agent.name %></td>
        <td>
          <p style="margin-top:15px;margin-bottom:15px">
            <% agent.assignments.select {|a| a.ownership > 0}.each do |a| %>
              <%= a.resource.name %>: <%= a.ownership.to_i %><br>
            <% end %>
          </p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/assigning_tasks_instances/_valuation_form.html.erb
<%= include_javascript "valuations/base.js.erb" %>
<%= include_javascript "valuations/tasks.js.erb" %>

<%= render 'layouts/text_banner', locals: { title: "Distribute Tasks - #{@instance.name}" } %>

<div class="page-content">
  <div class="wrap">
    <%= form_tag "#{@instance.id}/valuations/" + params[:p], honeypot: true do %>
      <%= render 'instances/valuation_form_header' %>
      <h2 style="margin-bottom:0">Evaluations</h2>
      <p>
        For each row, choose which task you'd prefer. Then, enter a <strong>multiplier</strong> to indicate how many times you'd be willing to complete your preferred task instead of completing the other task <strong>once</strong>. For example, if you believe that working the night shift is equal to working one and a half day shifts, select <strong>day shift</strong> and enter a multiplier of <strong>1.5</strong>. <a href = "<%= root_url + 'apps/tasks' %>" target="_blank">Click here</a> to learn how we use your evaluations to arrive at a fair division.</a>
      </p>

      <table class = "table">
        <thead>
          <tr>
            <td style="width:25%">Select Preferred Task</td>
            <td style="width:25%"></td>
            <td style="width:25%"></td>
            <td style="width:25%">Multiplier</td>
          </tr>
        </thead>
        <tbody>
        <% @instance.resources.each do |r| %>
          <%= hidden_field :values, r.id.to_s.to_sym %>
          <% next if r.id == @max_task.id %>
          <tr style="border-bottom:1px">
              <td>
                <%= radio_button_tag "comparisons[#{r.id}]", "first", true, class: "comparison" %>
                <%= label_tag "comparisons[#{r.id}]_first", @max_task.name, style: "display:inline" %>
              </td>
              <td>
                <%= radio_button_tag "comparisons[#{r.id}]", "second", false, class: "comparison" %>
                <%= label_tag "comparisons[#{r.id}]_second", r.name, style: "display:inline" %>
              </td>
              <td>
                <%= radio_button_tag "comparisons[#{r.id}]", "equal", false, class: "comparison" %>
                <%= label_tag "comparisons[#{r.id}]_equal", "No Preference", style: "display:inline" %>
              </td>
              <td>
                <%= text_field_tag "multipliers[#{r.id}]".to_sym, "1.0", class: "valuation_ipt " %>
              </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= submit_tag "Submit", class: "btn submit", onclick: "return checkValidTasks();" %>
      <%= render 'instances/descriptions' %>
    <% end %>
  </div>
</div>

app/views/assigning_tasks_instances/demo.html.erb
<% provide(:title, 'Live Demo: Distribute Tasks') %>
<% provide(:description, "Spliddit's tasks calculator fairly divides household chores, work shifts at a hospital, or any other set of tasks. With the live demo, you can experiment with the calculator and view the results on a single screen in a matter of seconds.") %>
<%= include_javascript 'demos/tasks.js' %>

<%= render 'banner' %>

<div class="page-content">
    <div class="wrap">
        <h1>Live Demo</h1><br>
        <div class="accordion curved" id="basics">The Basics<span class="symbol"></span></div>
        <div class="accordion-container">
            <div class="accordion-content">
                <form>
                    <div class="form-row">
                        <div class="form-row">
                            <p id="basics-error" class="error-msg error-text"></p>
                        </div>
                        <div class="form-row">
                            <h2 style="margin-bottom:0">Participants (comma-separated)</h2>
                            <%= text_field_tag :participants, "Alice, Bob", maxlength: 150, style: "width:90%" %>
                        </div>
                        <div class="form-row">
                            <h2 style="margin-bottom:0">Tasks (comma-separated)</h2>
                            <p class="description">For tasks that need to be completed more than once, put the number of times in parentheses.</p>
                            <%= text_field_tag :tasks, "Mow Lawn (2), Water Plants (7), Wash Dishes (14), Laundry (2)", maxlength: 150, style: "width:90%" %>
                        </div>
                        <%= submit_tag "   Update   ", class: "btn", onclick: "validateUpdateForm(); return false" %>
                    </div>
                </form>
            </div>
        </div>
        <div class="accordion" id="results">Results<span class="symbol"></span></div>
        <div class="accordion-container">
            <div class="accordion-content">
                <div id="update-results">
                    <p id="update-results-msg">Click the button to assign the tasks!</p>
                    <button id="submit-demo" type="button" class="btn update" onclick="checkBids(); return false">Get Results</button>
                </div>
                <br><br>
                <div id="results-table"></div>
            </div>
        </div>
    </div>
</div>

app/views/assigning_tasks_instances/index.html.erb
<% provide(:title, 'Distribute Tasks') %>
<% provide(:description, "Spliddit's tasks calculator fairly divides household chores, work shifts at a hospital, or any other set of tasks.") %>

<%= render 'banner' %>

<div class="page-content">
    <div class="wrap">
        <p>Spliddit's tasks calculator fairly divides household chores, work shifts at a hospital, or any other set of tasks. You begin by providing a list of tasks that you wish to assign (for example, morning shift, afternoon shift, night shift) and a list of participants. We then send the participants links where they specify how much they prefer each task relative to the others. Our algorithm uses these evaluations to propose a fair division of the tasks among the participants.</p>

        <div class="start-bar">
            <p style="text-align:center">
                <a class="btn" href="<%= root_url + 'apps/tasks/demo' %>" style="display:inline;margin:.5em">Live Demo</a>
                <a class="btn" href="<%= new_assigning_tasks_instance_path %>" style="display:inline;margin:.5em">Start <span>&raquo;</span></a>
            </p>
        </div><!--.start-bar-->  
    
        <h1>Fairness Properties</h1>

        <div class="content-block" id="max-share">

            <div class="align-right">

                <h2 class="mobile">Equitability</h2>

                <div class="equit">

                    <%= image_tag "equit/people.png", width: 221, height: 154, class: "people" %>
                    <%= image_tag "equit/large-box.png", width: 74, height: 60, class: "large-box" %>
                    <%= image_tag "equit/med-box.png", width: 56, height: 48, class: "med-box" %>
                    <%= image_tag "equit/small-box.png", width: 51, height: 39, class: "small-box" %>
                    <%= image_tag "equit/arm-guy.png", width: 70, height: 120, class: "arm-guy" %>
                    <%= image_tag "equit/arm-girl.png", width: 70, height: 120, class: "arm-girl" %>
                
                </div><!--.equit-->
                <p class="refresh equitr"><a href="#" title="Replay">refresh</a></p>
            </div><!--.align-right-->

            <div class="property-info left">

                <h2 class="desktop">Equitability</h2>
                <p>The assignment of tasks is equitable if all participants believe their workload is identical.</p>
                <p>This property is guaranteed with respect to the <a href = "#overview">lottery</a> produced by our method.</p>
            
            </div>

        </div><!--.content-block-->

        <div class="content-block last" id="efficient">

            <div class="align-left">

                <h2 class="mobile">Efficiency</h2>

                <div class="family-circle-2">
                    <div class="family-2">
                        <%= image_tag "itemshift/family-2.png", width: 241, height: 253, class: "bodies" %>
                        <%= image_tag "itemshift/baby-eyes1.png", width: 181, height: 155, class: "baby-eyes1" %>
                        <%= image_tag "itemshift/baby-eyes2.png", width: 181, height: 149, class: "baby-eyes2" %>
                        <%= image_tag "itemshift/lady-smile.png", width: 67, height: 36, class: "lady-smile" %>
                        <%= image_tag "itemshift/lady-frown.png", width: 31, height: 57, class: "lady-frown" %>
                        <%= image_tag "itemshift/football.png", width: 67, height: 36, class: "football-2" %>
                        <%= image_tag "itemshift/bottle.png", width: 31, height: 57, class: "bottle-2" %>
                        <%= image_tag "itemshift/purse.png", width: 59, height: 59, class: "purse-2" %>
                    </div><!--.family-->
                </div><!--.circle-->
                <p class="refresh effic"><a href="#" title="Replay">refresh</a></p>
            
            </div><!--.align-left-->
            
            <div class="property-info right">

                <h2 class="desktop">Efficiency</h2>
                <p>Our algorithm assigns the tasks in such a way that it would be impossible to find another assignment that benefits one participant without making another worse off.</p>
                <p>This property is guaranteed with respect to the <a href = "#overview">lottery</a> produced by our method.</p>
            
            </div><!--.property-info.right-->
            
        </div><!--.content-block-->

        <div class="start-bar">
            <p style="text-align:center">
                <a class="btn" href="<%= root_url + 'apps/tasks/demo' %>" style="display:inline;margin:.5em">Live Demo</a>
                <a class="btn" href="<%= new_assigning_tasks_instance_path %>" style="display:inline;margin:.5em">Start <span>&raquo;</span></a>
            </p>
        </div><!--.start-bar-->  

        <a name="overview"></a>
        <h1>Algorithm Overview</h1>
        <p>Spliddit implements the Egalitarian Equivalent solution of Pazner and Schmeidler to arrive at an assignment that equalizes and minimizes the perceived (expected) workload of each participant, but could potentially split tasks between participants (i.e., it is a fractional assignment). We compute this solution by solving a linear program.<!--using <a target="_blank" href="http://en.wikipedia.org/wiki/CPLEX">CPLEX</a>.--> Via another linear program we can then draw a suggested allocation from a lottery that rounds the fractional assignment up or down without changing the expected number of tasks performed by each participant. A lottery is an especially compelling solution for distributing tasks when Spliddit is used for this purpose on a regular basis, say weekly or monthly.</p>
        <p><strong>References:</strong> <a target="_blank" href="http://econdse.org/wp-content/uploads/2014/10/panzer-schmiedler-exchange.pdf">"Egalitarian Equivalent Allocations: A New Concept of Economic Equity"</a>, by Elisha A. Pazner and David Schmeidler; <a target="_blank" href = "http://faculty.chicagobooth.edu/eric.budish/research/Budish-Che-Kojima-Milgrom-2013-AER.pdf">"Designing Random Allocation Mechanisms: Theory and Applications"</a>, by Eric Budish, Yeon-Koo Che, Fuhito Kojima, and Paul Milgrom</p>

        <div class="start-bar">
            <p style="text-align:center">
                <a class="btn" href="<%= root_url + 'apps/tasks/demo' %>" style="display:inline;margin:.5em">Live Demo</a>
                <a class="btn" href="<%= new_assigning_tasks_instance_path %>" style="display:inline;margin:.5em">Start <span>&raquo;</span></a>
            </p>
        </div><!--.start-bar-->  

    </div><!--.wrap-->
</div><!--.page-content-->

app/views/assigning_tasks_instances/new.html.erb
<% provide(:title, 'New Distribute Tasks Instance') %>
<% provide(:description, "Enter a list of participants and a list of tasks (household chores, work shifts, or anything else) to get started. We'll then send everyone a link where they specify how much they prefer each task relative to the others.") %>
<%= include_javascript 'forms/base.js' %>
<%= include_javascript 'forms/tasks.js' %>

<%= render 'banner' %>

<div class="page-content">
  <div class="wrap">
    <%= form_tag assigning_tasks_instances_path + '/create', honeypot: true, autocomplete: "off" do %>
      <div class="form-row">
        <h2 style="margin-bottom:0">Tasks Description</h2>
        <p class="description">A short description of the tasks, chores, or shifts being assigned. Include the period of time over which the tasks are to be completed.
        </p>
        <%= text_field_tag :instance_name, nil, maxlength: 100, class: "ipt-med" %>
      </div>
      <%= render 'instances/participants_form', locals: { title: "Participants" } %>
      <br />
      <%= render 'instances/resources_form' %>
      <br />
      <%= render 'instances/admin_email_form' %>
      <%= render 'instances/submit' %>
    <% end %>
  </div>
</div>

app/views/assigning_tasks_instances/show.html.erb
<% provide(:title, 'Distribute Tasks') %>
<%= render "instances/show", controller_folder: "assigning_tasks_instances" %>