config/routes.rb
Spliddit::Application.routes.draw do
  
  resources :applications, path: "apps", only: [:index]

  post 'apps/rent/create', to: 'splitting_rent_instances#create'
  get 'apps/rent/demo', to: 'splitting_rent_instances#demo'
  resources :splitting_rent_instances, path: "apps/rent", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  post 'apps/goods/create', to: 'dividing_goods_instances#create'
  get 'apps/goods/demo', to: 'dividing_goods_instances#demo'
  resources :dividing_goods_instances, path: "apps/goods", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  post 'apps/credit/create', to: 'sharing_credit_instances#create'
  get 'apps/credit/demo', to: 'sharing_credit_instances#demo'
  resources :sharing_credit_instances, path: "apps/credit", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  resources :splitting_fare_instances, path: "apps/fare", only: [:index, :new]

  post 'apps/tasks/create', to: 'assigning_tasks_instances#create'
  get 'apps/tasks/demo', to: 'assigning_tasks_instances#demo'
  resources :assigning_tasks_instances, path: "apps/tasks", only: [:new, :show, :index] do
    member do
      post 'valuations/:pwd', action: 'submit_valuation', as: :submit_valuation
      post 'survey/:pwd', action: 'submit_survey', as: :submit_survey
    end
  end

  get '/about', to: 'static_pages#about'
  get '/feedback', to: 'feedbacks#feedback'
  get '/success', to: 'statuses#success'
  get '/error', to: 'statuses#error'
  get '/404', to: 'statuses#error404'
  get '/422', to: 'statuses#error500'
  get '/500', to: 'statuses#error500'

  post '/demo/create', to: 'demos#create'
  get '/demo/poll', to: 'demos#poll'

  post '/mailing_list/add', to: 'mailing_lists#mailing_list'

  post '/submit-feedback', to: 'feedbacks#submit_feedback'

  root to: "applications#index"
end

app/models/splitting_fare_instance.rb
class SplittingFareInstance < Instance

  attr_accessible :pickup_address, :total_fare, :currency, :error_message

  validates :pickup_address, presence: true, length: {minimum: 1, maximum: 100}

  validates :total_fare, numericality: {greater_than_or_equal: 0.0, less_than: 100000.0}, allow_nil: true
  validates :currency, length: { minimum: 3, maximum: 4}, allow_nil: true

  def run(attempt)
    # setup

    #Delayed::Worker.logger = Logger.new(File.join(Rails.root,'log','fare.log'))

    addresses = Hash.new
    agents.each do |a|
      addresses[a.id] = Hash.new
      addresses[a.id][:lat] = a.name.split("::")[1]
      addresses[a.id][:long] = a.name.split("::")[2]
    end

    # get TFF entity before computing any fares
    pickup_lat = pickup_address.split("::")[1]
    pickup_long = pickup_address.split("::")[2]
    uri = URI.parse("https://api.taxifarefinder.com/entity?key=#{TFF_API_KEY}&location=#{pickup_lat},#{pickup_long}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = JSON.parse(http.request(Net::HTTP::Get.new(uri.request_uri)).body)
    raise Error unless tff_check_response(response)
    entity_handle = response["handle"]

    # compute flat_fare and currency
    uri = tff_uri(entity_handle, pickup_lat, pickup_long, addresses[agents.first.id][:lat], addresses[agents.first.id][:long])
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = JSON.parse(http.request(Net::HTTP::Get.new(uri.request_uri)).body)
    raise Error unless tff_check_response(response)
    flat_fare = response["initial_fare"].to_f
    if !currency
      update_attribute(:currency, response["currency"]["int_symbol"].downcase)
    end

    # compute all pairs fares
    fares = all_pairs_fares_parallel(addresses, entity_handle, pickup_lat, pickup_long)

    # compute shapley values
    shapley_sum = 0.0
    shapley = Hash.new
    agents.each do |a|
      shapley[a.id] = 0.0
    end
    agents.map {|a| a.id}.permutation.each do |perm|
      agents.each do |a|
        idx = perm.index(a.id)
        if idx == 0
          shapley[a.id] += fares[a.id][:pickup]
        else
          Delayed::Worker.logger.debug("Before This")
          shapley[a.id] += get_route_fare(fares, perm[0..idx], flat_fare).first - get_route_fare(fares, perm[0..(idx-1)], flat_fare).first
          Delayed::Worker.logger.debug("After This")
        end
      end
    end

    # denominator is (# agents) factorial
    n_fact = (1..(agents.count)).inject(:*)
    agents.each do |a|
      shapley[a.id] /= n_fact
      shapley_sum += shapley[a.id]
    end

    # compute shortest route
    shortest_route = get_route_fare(fares, agents.map {|a| a.id}, flat_fare).second

    # create assignments
    assignments.delete_all
    agents.each do |a|
      if total_fare
        # user specified the total fare, so scale everything appropriately
        assignment = Assignment.new(price: shapley[a.id] * total_fare / shapley_sum, order: shortest_route.index(a.id))
      else
        assignment = Assignment.new(price: shapley[a.id], order: shortest_route.index(a.id))
      end
      assignment.agent_id = a.id
      assignment.instance_id = id
      assignment.save
    end

    #Delayed::Worker.logger.debug("Done Assignment")
  end


  def all_pairs_fares_sequential(addresses, entity_handle, pickup_lat, pickup_long)
    fares = Hash.new
    agents.each do |a|
      fares[a.id] = Hash.new
    end
    agents.each do |a1|
      # compute fare from pickup location to address
      uri = tff_uri(entity_handle, pickup_lat, pickup_long, addresses[a1.id][:lat], addresses[a1.id][:long])
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      response = JSON.parse(http.request(Net::HTTP::Get.new(uri.request_uri)).body)
      raise Error unless tff_check_response(response)
      fares[a1.id][:pickup] = response["total_fare"]

      agents.each do |a2|
        # check if same address (i.e. a1 == a2 or a1, a2 have same address)
        if addresses[a1.id][:lat] == addresses[a2.id][:lat] && addresses[a1.id][:long] == addresses[a2.id][:long]
          fares[a1.id][a2.id] = 0.0
        elsif a1.id < a2.id
          # a2.id < a1.id handled by symmetry
          uri = tff_uri(entity_handle, addresses[a1.id][:lat], addresses[a1.id][:long], addresses[a2.id][:lat], addresses[a2.id][:long])
          http = Net::HTTP.new(uri.host, uri.port)
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          response = JSON.parse(http.request(Net::HTTP::Get.new(uri.request_uri)).body)
          raise Error unless tff_check_response(response)
          fares[a1.id][a2.id] = response["total_fare"]
          fares[a2.id][a1.id] = fares[a1.id][a2.id] # assumes symmetry
        end
      end
    end
    fares
  end

  def all_pairs_fares_parallel(addresses, entity_handle, pickup_lat, pickup_long)
    fares = Hash.new
    fares["pickup"] = Hash.new
    agents.each do |a|
      fares[a.id] = Hash.new
    end

    EventMachine.run do
      multi = EventMachine::MultiRequest.new

      agents.each do |a1|
        uri = tff_uri(entity_handle, pickup_lat, pickup_long, addresses[a1.id][:lat], addresses[a1.id][:long])
        multi.add "pickup_#{a1.id}".to_sym, EventMachine::HttpRequest.new(uri,use_ssl: true).get
        agents.each do |a2|
          # see if same address (either a1 = a2 or live in same place)
          if addresses[a1.id][:lat] == addresses[a2.id][:lat] && addresses[a1.id][:long] == addresses[a2.id][:long]
            fares[a1.id][a2.id] = 0.0
          elsif a1.id < a2.id
            # a2.id < a1.id handled by symmetry
            uri = tff_uri(entity_handle, addresses[a1.id][:lat], addresses[a1.id][:long], addresses[a2.id][:lat], addresses[a2.id][:long])
            multi.add "#{a1.id}_#{a2.id}".to_sym, EventMachine::HttpRequest.new(uri,use_ssl: true).get
          end
        end
      end

      multi.callback do
        multi.responses[:callback].each do |key, http|
          source = key.to_s.split("_")[0]
          dest = key.to_s.split("_")[1]

          #Delayed::Worker.logger.debug("Got source/dest")

          response = JSON.parse(http.response)
          if !tff_check_response(response)
            EventMachine.stop
            raise Error
          end
          if source == "pickup"
            fares[dest.to_i][:pickup] = response["total_fare"]
          else
            fares[source.to_i][dest.to_i] = response["total_fare"]
            fares[dest.to_i][source.to_i] = response["total_fare"]
          end
        end

        multi.responses[:errback].each do |key, response|
          EventMachine.stop
          raise Error
        end

        EventMachine.stop
      end
    end
    fares
  end

  # Use TFF to calculate fare between two latlongs
  def tff_uri(handle, lat1, long1, lat2, long2)
    URI.parse("https://api.taxifarefinder.com/fare?key=#{TFF_API_KEY}&entity_handle=#{handle}&origin=#{lat1},#{long1}&destination=#{lat2},#{long2}")
  end

  # Check TFF Response for the status code, and raise Error if needed
  def tff_check_response(response)
    if response["status"] == "OK"
      return true
    elsif response["status"] == "ERROR"
      update_attribute(:error_message, "We've encountered an error. The most likely reason is that we were unable to find a route between the given addresses.")
      return false
    elsif response["status"] == "REQUEST_LIMIT_REACHED"
      update_attribute(:error_message, "Due to heavy traffic, we have exceeded our daily quota for the TaxiFareFinder service. Sorry for the inconvenience.")
      return false
    else
      update_attribute(:error_message, "We were unable to find routes between some of the addresses listed. Please make sure you've typed the addresses correctly and try again.")
      return false
    end
  end

  # compute cheapest route cost for a set of people
  def get_route_fare(costs, subset, flat_fare)
    return 0.0 unless subset.length > 0
    # loop through all routes (i.e. permutations of the set)
    min_fare = Float::INFINITY
    min_route = subset
    subset.permutation.each do |arr|
      cur_fare = costs[arr[0]][:pickup]
      for i in 0..(arr.length - 2)
        cur_fare += costs[arr[i]][arr[i+1]]
      end
      if cur_fare < min_fare
        min_fare = cur_fare
        min_route = arr
      end
    end

    # only include the flat fare once
    min_fare -= flat_fare * (subset.length - 1)

    return min_fare, min_route
  end

  def fare
    if total_fare
      total_fare
    else
      sum = 0.0
      assignments.each do |a|
        sum += a.price
      end
      sum
    end
  end

  # validators
  def min_agents
    2
  end

  def max_agents
    6
  end

  def min_resources
    0
  end

  def max_resources
    0
  end

  def resource_types
    []
  end

  def valuations_sum
    0
  end

  def decimal_valuations
    false
  end

  def min_bid
    0
  end
end

app/controllers/splitting_fare_instances_controller.rb
class SplittingFareInstancesController < InstancesController
  def redirect(instance, password)
    redirect_to splitting_fare_instance_path(instance, p: password)
  end
end

app/views/splitting_fare_instances/_banner.html.erb
<div class="innerpage-banner">
    <div class="wrap">
        <div class="page-title">
            <h1>Split Fare</h1>
        </div>
        <div class="banner-image">
          <%= image_tag "banners/splitting-fare.png", width: 250, height: 246, alt: "Split Fare" %>
        </div>
    </div><!--.wrap-->
</div><!--.innerpage-banner-->

app/views/splitting_fare_instances/index.html.erb
<% provide(:title, 'Split Taxi, Uber, or Lyft Fare') %>
<% provide(:description, "Spliddit's fare calculator helps to split taxi fares between multiple passengers. The fare calculator can also be used to divide the fares for ride-sharing services including Uber and Lyft.") %>

<%= render 'banner' %>

<div class="page-content">
    <div class="wrap">
        <p>Spliddit's fare calculator helps to fairly split taxi fares between multiple passengers. The fare calculator can also be used to divide the fares for ride-sharing services including Uber and Lyft. Simply enter the address you'd like to be picked up from, as well as the addresses of all the passengers, and we'll compute the results in seconds.  You can use the fare calculator before riding, and Spliddit will use <a href = "http://taxifarefinder.com" target = "_blank">TaxiFareFinder</a> to estimate fares. For the most accurate split, use the calculator at the end of your ride and enter the actual total fare.</p>

        <div class="start-bar">
            <p style="text-align:center">
                <a class="btn" href="<%= new_splitting_fare_instance_path %>">Start <span>&raquo;</span></a>
            </p>
        </div><!--.start-bar-->     

        <h1>Fairness Properties</h1>

        <div class="content-block" id="individual-rationality">

            <div class="align-right">

                <h2 class="mobile">Individual Rationality</h2>

                <div class="taxi1">
                    <%= image_tag "taxi/dollar.png", height: 53, width: 38, class: "dollar dollar1" %>
                    <%= image_tag "taxi/dollar.png", height: 53, width: 38, class: "dollar dollar2" %>
                    <%= image_tag "taxi/dollar.png", height: 53, width: 38, class: "dollar dollar3" %>
                    <%= image_tag "taxi/taxi.png", height: 201, width: 315, class: "taxi" %>
                    <%= image_tag "taxi/guy.png", height: 61, width: 38, class: "guy" %>
                    <%= image_tag "taxi/frown.png", height: 3, width: 13, class: "frown" %>
                    <%= image_tag "taxi/smile.png", height: 7, width: 14, class: "smile" %>
                    <%= image_tag "taxi/girl.png", height: 7, width: 14, class: "girl" %>
                    <%= image_tag "taxi/guy2.png", height: 60, width: 36, class: "guy2" %>
                </div>
                <p class="refresh taxi1r"><a href="#" title="Replay">refresh</a></p>
            
            </div><!--.align-right-->

            <div class="property-info left">

                <h2 class="desktop">Individual Rationality</h2>
                <p>The fare is split in a way that no passenger pays more than what she would pay if she took a taxi alone.</p>
                <p>This property is guaranteed, assuming fare estimates are accurate and fares are <a href="http://en.wikipedia.org/wiki/Subadditivity" target = "_blank">subadditive</a>. </p>

            </div><!--.property-info.left-->

        </div><!--.content-block-->

        <div class="content-block last" id="marginalism">

            <div class="align-left">

                <h2 class="mobile">Marginalism</h2>

                <div class="taxi2">
                    <%= image_tag "taxi/taxi.png", height: 201, width: 315, class: "staxi" %>
                    <%= image_tag "taxi/girl.png", height: 61, width: 38, class: "sgirl" %>
                    <%= image_tag "taxi/guy2.png", height: 60, width: 36, class: "sguy2" %>
                    <%= image_tag "taxi/guy-smile.png", height: 61, width: 38, class: "sguyb" %>
                    <%= image_tag "taxi/guy-smile.png", height: 61, width: 38, class: "sguyc" %>
                    <%= image_tag "taxi/guy-smile.png", height: 61, width: 38, class: "sguylast" %>
                    <%= image_tag "taxi/girl.png", height: 61, width: 38, class: "sgirllast" %>
                    <%= image_tag "taxi/guy2.png", height: 60, width: 36, class: "sguy2last" %>
                </div><!--.circle-->
                <p class="refresh taxi2r"><a href="#" title="Replay">refresh</a></p>
            
            </div><!--.align-left-->
            
            <div class="property-info right">

                <h2 class="desktop">Marginalism</h2>
                <p>Each passenger's share of the fare depends only on her marginal contribution to the (estimated) fare when joining each possible ride to some of the destinations.</p>
                <p>This property is guaranteed.</p>
            
            </div><!--.property-info.right-->
            
        </div><!--.content-block-->

        <div class="start-bar">
            <p style="text-align:center">
                <a class="btn" href="<%= new_splitting_fare_instance_path %>">Start <span>&raquo;</span></a>
            </p>
        </div><!--.start-bar-->    



        <h1>Algorithm Overview</h1>
        <p>We first compute the fares between each pair of addresses using <a href = "http://taxifarefinder.com" target="_blank">TaxiFareFinder</a>. We use these estimates to calculate the fare of a hypothetical ride to every subset of destinations, thereby obtaining the cost of every subset of passengers. The payment of an individual passenger is her Shapley value: her average (roughly speaking) marginal contribution to the cost of any subset of other passengers. Assuming the entire fare must be split, the Shapley Value is provably the <b>unique</b> method that satisfies <a href="#marginalism">marginalism</a> together with another basic property called anonymity. When the estimated fare is different from the actual fare, we simply scale the individual payments to match the actual fare; this provably preserves all the guarantees. </p> 
        <p><strong>Reference:</strong> <a target="_blank" href="http://en.wikipedia.org/wiki/Shapley_value">Shapley Value (Wikipedia)</a></p>
        <!-- <p><a class="no-underline" target="_blank" href = "http://taxifarefinder.com"><%= image_tag "taxifarefinder.png" %></a></p> -->
        
        <div class="start-bar">
            <p style="text-align:center">
                <a class="btn" href="<%= new_splitting_fare_instance_path %>">Start <span>&raquo;</span></a>
            </p>
        </div><!--.start-bar-->     



    </div><!--.wrap-->
</div><!--.page-content-->

app/views/splitting_fare_instances/new.html.erb
<% provide(:title, 'New Split Fare Instance') %>
<% provide(:description, "Enter the pickup and dropoff addresses below, and Spliddit's fare calculator will split the cost of your ride in seconds.") %>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLEKzvczrTGKQDOzvCAs56nqdSZlgpQhU&libraries=places"></script>
<%= include_javascript 'forms/fare.js' %>

<%= render 'banner' %>

<div class="page-content">
    <div class="wrap">
        <div class="accordion curved" id="addresses">Enter Addresses<span class="symbol"></span></div>
        <div class="accordion-container">
            <div class="accordion-content">
                <form onkeypress="return event.keyCode != 13;" onsubmit="return false;" autocomplete="off">
                    <div class="form-row">
                        <div class="form-row">
                            <p id="addresses-error" class="error-msg error-text"></p>
                        </div>
                        <div class="form-row">
                            <h2 style="margin-bottom:0">Pickup Location</h2>
                            <p class="description">Enter the address from which everyone will be picked up.</p>
                            <%= text_field_tag :pickup, nil, class: "loc", autocomplete: "off" %>
                        </div>
                        <h2 style="margin-bottom:0">Dropoff Locations</h2>
                        <p class="description">Enter the address of each passenger (between 2 and 6). If multiple people are being dropped off at the same location, list the address multiple times. The order doesn't matter; we will compute the cheapest route for you.</p>
                        <table>
                            <tbody>
                                <tr><td>1</td><td><%= text_field_tag :dropoff_1, nil, class: "loc", autocomplete: "off" %></td></tr>
                                <tr><td>2</td><td><%= text_field_tag :dropoff_2, nil, class: "loc", autocomplete: "off" %></td></tr>
                                <tr><td>3</td><td><%= text_field_tag :dropoff_3, nil, class: "loc", autocomplete: "off" %></td></tr>
                                <tr><td>4</td><td><%= text_field_tag :dropoff_4, nil, class: "loc", autocomplete: "off" %></td></tr>
                                <tr><td>5</td><td><%= text_field_tag :dropoff_5, nil, class: "loc", autocomplete: "off" %></td></tr>
                                <tr><td>6</td><td><%= text_field_tag :dropoff_6, nil, class: "loc", autocomplete: "off" %></td></tr>
                                <!-- Dummy used to stop Chrome Autofill -->
                                <tr style="display:none"><td></td><td><%= text_field_tag :dummy, nil, class: "loc" %></td></tr>
                            </tbody>
                        </table>
                        <div class="form-row">
                            <h2 style="margin-bottom:0">Total Fare (Optional)</h2>
                            <p class="description">If you know the total cost of the ride (including tip), enter it below. Otherwise, we will estimate the fare for you using <a href = "http://taxifarefinder.com" target = "_blank">TaxiFareFinder</a>.</p>
                            <span class="addon">
                                <%= select_tag "currency".to_sym, 
                                    options_for_select([["$","usd"],
                                                        ["€","euro"],
                                                        ["£","gbp"],
                                                        ["¥","jpy"],
                                                        ["₪","ils"]], params[:currency]) %>
                                                        <!--["₹","inr"]]-->
                            </span>
                            <%= text_field_tag :total_fare, nil, maxlength: 7, style: "width:100px; text-align:right" %>
                        </div>
                        <div class="form-row">
                            <h2 style="margin-bottom:0">Email Address (Optional)</h2>
                            <p class="description">Enter an email address if you'd like us to send you the results in addition to displaying them below.</p>
                            <%= text_field_tag :admin_email, nil, maxlength: 50, class: "ipt-small" %>
                        </div>
                        <%= submit_tag "   Next   ", class: "btn", onclick: "validateAddressesForm(true); return false" %>
                    </div>
                </form>
            </div>
        </div>
        <div class="accordion" id="results">Compute Fares<span class="symbol"></span></div>
        <div class="accordion-container">
            <div class="accordion-content">
                <div id="update-results">
                    <p id="update-results-msg">Click the button to split the fare!</p>
                    <button id="submit-demo" type="button" class="btn update" onclick="submit(); return false">Get Results</button>
                </div>
                <br><br>
                <div id="results-table"></div>
            </div>
        </div>
    </div>
</div>